const nome = prompt('Digite seu nome completo:')
document.body.innerHTML += `Seu nome é: <strong>${nome}</strong><br/>`
document.body.innerHTML += `Seu nome tem: <strong>${nome.replaceAll(' ', '').length} letras</strong><br/>`
document.body.innerHTML += `A segunda letra do seu nome é: <strong>${nome[1]}</strong><br/>` //${nome.charAt(1)}
document.body.innerHTML += `Qual o primeiro indice da letra O no seu nome? <strong>${nome.indexOf('o')}</strong><br/>`
document.body.innerHTML += `Qual o ultimo indice da letra O no seu nome? <strong>${nome.lastIndexOf('o')}</strong><br/>`
document.body.innerHTML += `As últimas 3 letras do seu nome são: <strong>${nome.slice(-3)}</strong><br/>` 
document.body.innerHTML += `As palavras do seu nome são: <strong>${nome.split(' ')}</strong><br/>`
document.body.innerHTML += `Seu nome com letras maiúsculas: <strong>${nome.toUpperCase()}</strong><br/>`
document.body.innerHTML += `Seu nome com letra minúsculas: <strong>${nome.toLowerCase()}</strong><br/>`